SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC dbo.AUDIT_prc_CommitUndo
AS
COMMIT TRAN
SET IMPLICIT_TRANSACTIONS OFF
DROP TABLE ##UndoLog
DROP TABLE ##UndoColumns
RETURN @@ERROR
GO
